"""Send weekly welfare report via email after HDX publishing.

Composes an HTML summary of the latest data ingestion and attaches
the HXL-tagged CSV datasets as inline content. Sends via a configurable
HTTP mail API endpoint.

Required environment variables:
  MAIL_API_BASE_URL  Base URL of the mail API
  MAIL_API_KEY       API key for authentication
  REPORT_TO          Comma-separated recipient list
"""

import os
import sys
import json
import logging
import uuid
from datetime import datetime, timezone

import pandas as pd

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

HDX_OUTPUT_DIR = os.path.join("reports", "hdx")

DATASET_META = [
    {
        "file": "global-economic-indicators.hxl.csv",
        "title": "Global Economic Indicators (World Bank)",
        "source": "World Bank API",
    },
    {
        "file": "global-health-indicators.hxl.csv",
        "title": "Global Health Indicators (WHO GHO)",
        "source": "WHO Global Health Observatory",
    },
    {
        "file": "disaster-alerts.hxl.csv",
        "title": "Global Disaster Alerts (GDACS)",
        "source": "GDACS RSS Feed",
    },
    {
        "file": "food-price-indices.hxl.csv",
        "title": "Global Food Price Indices (FAO)",
        "source": "FAOSTAT",
    },
]


def _dataset_summary(filepath):
    """Return (row_count, size_kb) for a CSV, skipping the HXL tag row."""
    if not os.path.exists(filepath):
        return None
    try:
        df = pd.read_csv(filepath, skiprows=[1], low_memory=False)
        size_kb = os.path.getsize(filepath) / 1024
        return len(df), round(size_kb, 1)
    except Exception as e:
        logger.warning(f"Cannot summarise {filepath}: {e}")
        return None


def compose_html_body():
    """Build an HTML email body summarising the latest datasets."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = []
    for meta in DATASET_META:
        path = os.path.join(HDX_OUTPUT_DIR, meta["file"])
        info = _dataset_summary(path)
        if info:
            count, size = info
            rows.append(
                f"<tr>"
                f"<td>{meta['title']}</td>"
                f"<td>{meta['source']}</td>"
                f"<td style='text-align:right'>{count:,}</td>"
                f"<td style='text-align:right'>{size:,.1f} KB</td>"
                f"</tr>"
            )
        else:
            rows.append(
                f"<tr>"
                f"<td>{meta['title']}</td>"
                f"<td>{meta['source']}</td>"
                f"<td colspan='2' style='color:#999'>not available</td>"
                f"</tr>"
            )

    table_rows = "\n".join(rows)

    return f"""\
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a1a;">
<h2 style="margin: 0 0 16px;">Global Welfare Monitor - Weekly Report</h2>
<p>Generated: <strong>{now}</strong></p>
<p>The following datasets have been updated and published to
<a href="https://data.humdata.org/organization/evomap">HDX (Humanitarian Data Exchange)</a>.</p>

<table border="1" cellpadding="6" cellspacing="0"
       style="border-collapse:collapse; width:100%; font-size:14px;">
<thead style="background:#f5f5f5;">
  <tr>
    <th align="left">Dataset</th>
    <th align="left">Source</th>
    <th align="right">Rows</th>
    <th align="right">Size</th>
  </tr>
</thead>
<tbody>
{table_rows}
</tbody>
</table>

<h3>Data Sources</h3>
<ul>
  <li><strong>World Bank</strong> - GDP per capita, poverty headcount, population, school enrollment, health expenditure</li>
  <li><strong>WHO GHO</strong> - Life expectancy, infant/under-five/maternal/NCD mortality</li>
  <li><strong>GDACS</strong> - Real-time earthquake, flood, cyclone, drought alerts</li>
  <li><strong>FAOSTAT</strong> - Consumer food price indices by country</li>
</ul>

<p>Full datasets are available on
<a href="https://data.humdata.org/organization/evomap">HDX</a> or the
<a href="https://evomap.github.io/global-welfare-monitor/">project dashboard</a>.</p>

<hr style="border: none; border-top: 1px solid #e5e5e5; margin: 24px 0;">
<p style="color: #999; font-size: 12px;">
  This report is automatically generated by the
  <a href="https://github.com/EvoMap/global-welfare-monitor">Global Welfare Monitor</a>
  pipeline.
</p>
</body>
</html>"""


def send_report():
    """Compose and send the weekly welfare report email."""
    base_url = os.environ.get("MAIL_API_BASE_URL", "").rstrip("/")
    api_key = os.environ.get("MAIL_API_KEY", "")
    mail_to = os.environ.get("REPORT_TO", "")

    if not base_url or not api_key:
        logger.warning("MAIL_API_BASE_URL or MAIL_API_KEY not set. Skipping email.")
        return

    recipients = [addr.strip() for addr in mail_to.split(",") if addr.strip()]
    if not recipients:
        logger.warning("REPORT_TO is empty. Skipping email.")
        return

    now_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"Global Welfare Monitor - Weekly Report ({now_date})"
    html_body = compose_html_body()

    url = f"{base_url}/api/v1/mails/send"
    headers = {
        "Content-Type": "application/json",
        "X-API-Key": api_key,
    }

    import urllib.request

    for recipient in recipients:
        payload = json.dumps({
            "to": [recipient],
            "subject": subject,
            "body": html_body,
            "idempotency_key": str(uuid.uuid4()),
        }).encode("utf-8")

        req = urllib.request.Request(url, data=payload, headers=headers, method="POST")

        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                status = resp.status
                logger.info(f"Email sent to {recipient} (status {status})")
        except Exception as e:
            logger.error(f"Failed to send email to {recipient}: {e}")
            sys.exit(1)

    logger.info(f"All {len(recipients)} report emails sent")


if __name__ == "__main__":
    send_report()
