"""Send weekly welfare report via email after HDX publishing.

Composes an HTML summary of the latest data ingestion and attaches
the HXL-tagged CSV datasets. Uses SMTP (compatible with AWS SES,
Gmail, or any standard SMTP relay).

Required environment variables:
  SMTP_HOST        SMTP server hostname
  SMTP_PORT        SMTP port (default 587)
  SMTP_USER        SMTP username / access key
  SMTP_PASS        SMTP password / secret key
  REPORT_FROM      Sender address (e.g. noreply@evomap.ai)
  REPORT_TO        Comma-separated recipient list
"""

import os
import sys
import smtplib
import logging
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

import pandas as pd

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

HDX_OUTPUT_DIR = os.path.join("reports", "hdx")
DATA_DIR = os.environ.get("DATA_DIR", "data")

DATASET_META = [
    {
        "file": "global-economic-indicators.hxl.csv",
        "title": "Global Economic Indicators (World Bank)",
        "source": "World Bank API",
    },
    {
        "file": "global-health-indicators.hxl.csv",
        "title": "Global Health Indicators (WHO GHO)",
        "source": "WHO Global Health Observatory",
    },
    {
        "file": "disaster-alerts.hxl.csv",
        "title": "Global Disaster Alerts (GDACS)",
        "source": "GDACS RSS Feed",
    },
    {
        "file": "food-price-indices.hxl.csv",
        "title": "Global Food Price Indices (FAO)",
        "source": "FAOSTAT",
    },
]


def _dataset_summary(filepath):
    """Return (row_count, columns, size_kb) for a CSV, skipping the HXL tag row."""
    if not os.path.exists(filepath):
        return None
    try:
        df = pd.read_csv(filepath, skiprows=[1], low_memory=False)
        size_kb = os.path.getsize(filepath) / 1024
        return len(df), list(df.columns), round(size_kb, 1)
    except Exception as e:
        logger.warning(f"Cannot summarise {filepath}: {e}")
        return None


def compose_html_body():
    """Build an HTML email body summarising the latest datasets."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = []
    for meta in DATASET_META:
        path = os.path.join(HDX_OUTPUT_DIR, meta["file"])
        info = _dataset_summary(path)
        if info:
            count, cols, size = info
            rows.append(
                f"<tr>"
                f"<td>{meta['title']}</td>"
                f"<td>{meta['source']}</td>"
                f"<td style='text-align:right'>{count:,}</td>"
                f"<td style='text-align:right'>{size:,.1f} KB</td>"
                f"</tr>"
            )
        else:
            rows.append(
                f"<tr>"
                f"<td>{meta['title']}</td>"
                f"<td>{meta['source']}</td>"
                f"<td colspan='2' style='color:#999'>not available</td>"
                f"</tr>"
            )

    table_rows = "\n".join(rows)

    html = f"""\
<html>
<body style="font-family: -apple-system, Helvetica, Arial, sans-serif; color: #333; max-width: 680px;">
<h2>Global Welfare Monitor - Weekly Report</h2>
<p>Generated: <strong>{now}</strong></p>
<p>The following datasets have been updated and published to
<a href="https://data.humdata.org/organization/evomap">HDX (Humanitarian Data Exchange)</a>.</p>

<table border="1" cellpadding="6" cellspacing="0"
       style="border-collapse:collapse; width:100%; font-size:14px;">
<thead style="background:#f5f5f5;">
  <tr>
    <th align="left">Dataset</th>
    <th align="left">Source</th>
    <th align="right">Rows</th>
    <th align="right">Size</th>
  </tr>
</thead>
<tbody>
{table_rows}
</tbody>
</table>

<h3>Data Sources</h3>
<ul>
  <li><strong>World Bank</strong> - GDP per capita, poverty headcount, population, school enrollment, health expenditure</li>
  <li><strong>WHO GHO</strong> - Life expectancy, infant/under-five/maternal/NCD mortality</li>
  <li><strong>GDACS</strong> - Real-time earthquake, flood, cyclone, drought alerts</li>
  <li><strong>FAOSTAT</strong> - Consumer food price indices by country</li>
</ul>

<p>Full datasets are attached as HXL-tagged CSVs. You can also view them on
<a href="https://data.humdata.org/organization/evomap">HDX</a> or the
<a href="https://evomap.github.io/global-welfare-monitor/">project dashboard</a>.</p>

<hr style="border:none; border-top:1px solid #ddd; margin:20px 0;">
<p style="font-size:12px; color:#999;">
  This report is automatically generated by the
  <a href="https://github.com/EvoMap/global-welfare-monitor">Global Welfare Monitor</a>
  pipeline, a project of the EvoMap AI agent swarm.
</p>
</body>
</html>"""
    return html


def send_report():
    """Compose and send the weekly welfare report email."""
    smtp_host = os.environ.get("SMTP_HOST")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASS")
    mail_from = os.environ.get("REPORT_FROM", "noreply@evomap.ai")
    mail_to = os.environ.get("REPORT_TO", "admin@evomap.ai")

    if not smtp_host or not smtp_user or not smtp_pass:
        logger.error(
            "SMTP_HOST, SMTP_USER, and SMTP_PASS must be set. Skipping email."
        )
        sys.exit(1)

    recipients = [addr.strip() for addr in mail_to.split(",") if addr.strip()]

    now_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"Global Welfare Monitor - Weekly Report ({now_date})"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = mail_from
    msg["To"] = ", ".join(recipients)

    html_body = compose_html_body()
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    attached = 0
    for meta in DATASET_META:
        filepath = os.path.join(HDX_OUTPUT_DIR, meta["file"])
        if not os.path.exists(filepath):
            continue
        try:
            part = MIMEBase("text", "csv")
            with open(filepath, "rb") as f:
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition", "attachment", filename=meta["file"]
            )
            msg.attach(part)
            attached += 1
        except Exception as e:
            logger.warning(f"Failed to attach {meta['file']}: {e}")

    logger.info(
        f"Sending report to {recipients} ({attached} attachments) via {smtp_host}:{smtp_port}"
    )

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(mail_from, recipients, msg.as_string())
        logger.info("Email sent successfully")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        sys.exit(1)


if __name__ == "__main__":
    send_report()
